# -*- coding: utf-8 -*-
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 ComfyUI-H3-Latent-Relay contributors
# 第三方出处与许可见 THIRD-PARTY-NOTICES.md
"""H3 Latent Relay · 核心算法层（纯张量，零 GPU、零模型、可离线单测）

【这是什么】
MiniMax-H3 多段续接的 **latent 桥**：把上一段的 AV latent 切出尾段，
以 `minimax_keyframes`（多块，按 `resolved_frame_index` 排位）
+ `minimax_refs`（音频）注入本段的 conditioning。

【与像素续接的区别（本包存在的理由）】
  像素续接：上一段 mp4 → 解码帧 → VAE 重编码 → 单块 keyframe @frame0
            —— 多一次 VAE 往返，有量化损失，且曝光可能漂移。
  latent 桥：上一段 AV latent → 直接切尾段 → 多块 keyframe 按位置
            —— 零重编码，与采样时的 latent 逐位同源。

二者走的是**同一个 ComfyUI 原生协议**（`minimax_keyframes`），
故可互换；本包提供后者，并保持与前者完全兼容的键结构。

【协议出处（本机实测，非推测）】
  comfy/ldm/minimax/model.py:376
      cond_t = cursor + FRAME_RESCALE * kf["resolved_frame_index"]
  comfy/model_base.py:2186-2196
      keyframes = kwargs.get("minimax_keyframes")   → payload["keyframes"]
      refs      = kwargs.get("minimax_refs")        → payload["refs"]
  → 原生支持任意位置的 keyframe 锚，无需任何 monkey patch。

【帧 / latent 网格】
  H3 VAE 的时序跨度为 (1,4,4,4,4)：每 5 个 latent token 覆盖 17 像素帧。
  因此**只有落在网格上的窗口**才能被整步切出，合法窗口（GUIDE_RUNS）：
      1, 5, 22, 39, 56, 73, 90, 107, 124 ...
  22 帧 = 7 个 latent token；39 帧 = 12 个 token。
  不在网格上 → raise（而不是悄悄挪一格，那会渲染出位移的接缝）。
"""

from __future__ import annotations

# 本包由单文件 `relay_core.py` 拆分而来（2026-10-07）。
# 这里**全量再导出**每个子模块的顶层名字（含下划线开头的内部名）——
# 目的是让 `relay_core.xxx` 这个**公开身份**逐字不变：
# `nodes.py` / `tests/` / `tools/` / `exp/` 一行都不用改。
# 新增能力时：先想它属于哪个子模块，再在下面补一行导出。

# —— _grid：网格常量与网格工具（H3 VAE 的 5+17k 时序网格、窗口吸附、常量导出键）。
from ._grid import (
    AUDIO_HZ,
    FPS,
    FRAME_PER_TOKEN,
    FRAME_RESCALE,
    GUIDE_RUNS,
    KEY_EXPORT_FRAMES,
    KEY_EXPORT_TAIL_AUDIO,
    KEY_EXPORT_TAIL_VIDEO,
    pixel_frames,
    self_check,
    snap_guide_run,
    step_offsets,
    steps_for_frames,
)

# —— latent：latent 取流 / 尾段切片 / AV latent 落盘往返 / 裁头重叠。
from .latent import (
    _LATENT_META_KEY,
    audio_from_latent,
    audio_tail_from_latent,
    load_av_latent,
    save_av_latent,
    streams_from_latent,
    trim_audio_head,
    trim_head_frames,
    video_from_latent,
    video_tail_from_latent,
)

# —— audio：音频缝（patch + 床环铺）· 孤立瞬态抑制 declick · 音频读存 · 多段音频拼接。
from .audio import (
    AUDIO_DECLICK_BG_PCT,
    AUDIO_DECLICK_BG_WIN_MS,
    AUDIO_DECLICK_CUT_GUARD_S,
    AUDIO_DECLICK_EDGE_REL,
    AUDIO_DECLICK_FADE_MS,
    AUDIO_DECLICK_FALLBACK_S,
    AUDIO_DECLICK_MAX_EVENTS,
    AUDIO_DECLICK_MAX_LEN_MS,
    AUDIO_DECLICK_PROBE_S,
    AUDIO_DECLICK_QUIET_DBFS,
    AUDIO_DECLICK_QUIET_REL,
    AUDIO_DECLICK_RATIO,
    AUDIO_DECLICK_SCOPE_ALL,
    AUDIO_ENCODER_PRIME_MS,
    AUDIO_LOUDNESS_MAX_CUT_DB,
    AUDIO_LOUDNESS_MAX_GAIN_DB,
    AUDIO_LOUDNESS_MIN_VOICED,
    AUDIO_LOUDNESS_PCT,
    AUDIO_LOUDNESS_PEAK_CEIL,
    AUDIO_LOUDNESS_TARGET_DBFS,
    AUDIO_LOUDNESS_TOL_DB,
    AUDIO_LOUDNESS_WIN_S,
    AUDIO_SEAM_BED_FLOOR_DB,
    AUDIO_SEAM_BED_GAIN_MAX_DB,
    AUDIO_SEAM_BED_SELECT,
    AUDIO_SEAM_BED_TILE_VOICED_FRAC,
    AUDIO_SEAM_BED_VOICED_FRAC,
    AUDIO_SEAM_BED_VOICED_K,
    AUDIO_SEAM_BED_VOICED_SUSTAIN,
    AUDIO_SEAM_FADE,
    AUDIO_SEAM_PATCH,
    AUDIO_SEAM_PATCH_GUARD_CENT_HZ,
    AUDIO_SEAM_PATCH_GUARD_FLAT,
    AUDIO_SEAM_PATCH_GUARD_HOP,
    AUDIO_SEAM_PATCH_GUARD_K,
    AUDIO_SEAM_PATCH_GUARD_LAYERS,
    AUDIO_SEAM_PATCH_GUARD_MARGIN_S,
    AUDIO_SEAM_PATCH_GUARD_MIN_S,
    AUDIO_SEAM_PATCH_GUARD_STEP_DB,
    AUDIO_SEAM_PATCH_GUARD_WIN,
    AUDIO_SEAM_TILE,
    _AUDIO_META_KEY,
    _DeclickCtx,
    _audio_parts,
    _declick_bg_at_cut,
    _declick_envelope,
    _declick_fade_in_at_cut,
    _declick_fill,
    _declick_find_events,
    _declick_report,
    _declick_suppress,
    _frame_rms,
    _guard_features,
    _guard_layers_pass,
    _match_channels,
    _resample_to,
    _rms_db,
    _speech_onset_in_head,
    _voiced_frac_from_frames,
    audio_seam_patch,
    audio_to_fp32,
    bed_source_window_len,
    bed_window_voiced_fraction,
    build_bed,
    declick_gate,
    declick_on_segment,
    declick_transients,
    find_nonvoiced_bed_window,
    join_audio_segments,
    load_audio,
    normalize_loudness,
    nonvoiced_candidates,
    pick_bed_window,
    quietest_window,
    save_audio,
    speech_rms_db,
    target_level,
)

# —— plan：续接计划（RelayPlan / plan_relay / apply_relay）· 音频参考窗自动定长 · 漂移对策。
from .plan import (
    ANCHOR_VOICED_MARGIN_S,
    ANCHOR_VOICED_MIN_FRAC,
    AUDIO_REF_MAX_S,
    AUDIO_REF_MIN_VOICED_S,
    AUDIO_REF_OFFICIAL_MAX,
    AUDIO_REF_VOICE_REL,
    RelayPlan,
    RUN_ID_TYPES,
    VOICE_ANCHOR_MIN_STD,
    _anchor_position,
    _partition_anchors,
    _voice_anchor_audio,
    _voice_anchor_tail,
    _voiced_grids,
    anchor_window_start,
    apply_relay,
    auto_audio_ref_seconds,
    build_anchor_ref,
    collect_run_ids,
    count_official_audio_refs,
    match_stats,
    plan_relay,
    plan_run_id_sync,
    resolve_run_id,
    sync_run_id,
)

# —— seam：接缝自检与画质观测（沉降检测 / 硬跳 / 锐度 / 色档 / 复现残留 / 直方图与白平衡）。
from .seam import (
    ADVISE_WITHIN,
    ANALYSIS_SHORT_SIDE,
    ANALYSIS_SHORT_SIDE_ALT,
    BASELINE_FLOOR_REL,
    BLUR_COLLAPSE_RATIO,
    BLUR_COLLAPSE_RATIO_SHARP,
    BLUR_RECOVER_RATIO,
    BLUR_ZONE_RATIO,
    BOUNDARY_JUMP_WARN,
    GRADE_DEV_FLOOR,
    GRADE_DEV_Z,
    JUMP_RATIO,
    LOWFREQ_PULL_BLUR,
    LOWFREQ_PULL_FRAMES,
    LOWFREQ_PULL_WEIGHT,
    MATCH_PREV_FRAMES,
    MATCH_PREV_GAIN_MAX,
    MATCH_PREV_OFF_MAX,
    MATCH_PREV_STATS_FRAMES,
    MATCH_PREV_WEIGHT,
    MAX_SETTLE,
    POST_BODY_DISP_MAX,
    QUANTILE_MAX_ELEMS,
    QUANTILE_SAMPLE_ELEMS,
    REPEAT_MAE,
    REPEAT_MIN_RUN,
    REPEAT_SCAN,
    SEAM_GHOST_ALPHA,
    SEAM_GHOST_FRAMES,
    SETTLE_CAP,
    SETTLE_CROSS_SCALE,
    SETTLE_RECOVER_TARGET,
    SETTLE_REF_OFF,
    SETTLE_REPEAT_PATH,
    SETTLE_SCAN,
    SETTLE_SHARPEN,
    SETTLE_SHARPEN_FRAMES,
    SETTLE_SHARPEN_MAX,
    Z_JUMP,
    _LAP_KERNELS,
    _abs_max,
    _baseline_floor,
    _blur_collapse,
    _box_blur_hwc,
    _canonicalize,
    _frame_diffs,
    _quantile_capped,
    _robust_stats,
    _sharpness,
    borrow_detail_from_body,
    boundary_jump_ratio,
    deconv_head_zone,
    describe_head_jump,
    describe_latent,
    detect_settle,
    find_head_jump,
    head_metrics,
    lowfreq_pull,
    match_hist_head_to_body,
    match_prev_stats,
    match_white_balance,
    observation_profile,
    robust_body,
    scan_head_jump,
    scan_head_repeat,
    seam_crossfade,
    seam_ghost_blend,
    settle_compensate,
    sharpen_head_zone,
    trim_jump_curve,
    unsharp_frames,
)

# —— bridge：拷贝桥（latent 硬拷贝 + 噪声掩码 + 前缀权重族）· build_continue_latent。
from .bridge import (
    AUDIO_RELEASE_TICKS,
    BLEND_SHAPES,
    BLEND_SHAPE_DEFAULT,
    MASK_MODES,
    SEAM_BLEND_TOP,
    SEAM_BLEND_TOP_MAX,
    SEAM_MIN_FLOOR,
    SEAM_MIN_MASK,
    SEAM_RAMP_TOP,
    SEAM_RAMP_TOP_MAX,
    SEAM_RAMP_TOP_MIN,
    SEAM_TAPER_TOKENS,
    SEAM_WINDOW_TOP,
    WINDOW_SHAPES,
    WINDOW_SHAPE_DEFAULT,
    _nested_pair,
    _window_shape,
    build_continue_latent,
    prefix_blend_weights,
    prefix_ramp_weights,
    prefix_taper_weights,
    prefix_window_weights,
)

# —— metrics：🧪 实验层只读观测（DTW 对齐代价 / 外观统计 / 漂移曲线）。
from .metrics import (_dtw_feat, drift_curve, dtw_residual, head_repeat_dtw, segment_appearance_stats)

# —— concat：多段拼接成片（PyAV）+ 输出挑选取回 + 提交图定序。
from .concat import (
    AV_CONCAT_VIDEO_EXTS,
    LOSSLESS_AUDIO_CODECS,
    PCM_UI_KEY,
    _FILE_PATH_KEYS,
    _ILLEGAL_IN_NAME,
    _av_module,
    _decode_pcm,
    _file_record,
    _iter_file_records,
    _link_source,
    _load_pcm_sidecar,
    _looks_like_path,
    _passthrough_video_stream,
    _path_is_abs,
    _path_split,
    _secs,
    _video_codec,
    assemble_mp4_segments,
    assert_assembled,
    assert_segments_joinable,
    concat_mp4_segments,
    graph_downstream_rank,
    pick_pcm_outputs,
    pick_video_outputs,
    probe_mp4,
)

# —— upscale：画质域 AV latent 分块放大（拆包 → 逐块 → 回包）。
from .upscale import (
    UPSCALE_CHUNK_FRAMES_DEFAULT,
    UPSCALE_OVERLAP_DEFAULT,
    _pad_frames,
    max_upscale_chunks,
    temporal_tile_upscale,
    upscale_chunk_plan,
)

# —— prompt：词分发（连跑时「第 k 段喂第 k 块词」）。
from .prompt import (PROMPT_SEPARATOR_MIN_DASHES, _lines_like_js, pick_prompt_block, split_prompt_blocks)

__all__ = [
    "ADVISE_WITHIN",
    "ANALYSIS_SHORT_SIDE",
    "ANALYSIS_SHORT_SIDE_ALT",
    "ANCHOR_VOICED_MARGIN_S",
    "ANCHOR_VOICED_MIN_FRAC",
    "AUDIO_DECLICK_BG_PCT",
    "AUDIO_DECLICK_BG_WIN_MS",
    "AUDIO_DECLICK_CUT_GUARD_S",
    "AUDIO_DECLICK_EDGE_REL",
    "AUDIO_DECLICK_FADE_MS",
    "AUDIO_DECLICK_FALLBACK_S",
    "AUDIO_DECLICK_MAX_EVENTS",
    "AUDIO_DECLICK_MAX_LEN_MS",
    "AUDIO_DECLICK_PROBE_S",
    "AUDIO_DECLICK_QUIET_DBFS",
    "AUDIO_DECLICK_QUIET_REL",
    "AUDIO_DECLICK_RATIO",
    "AUDIO_DECLICK_SCOPE_ALL",
    "AUDIO_ENCODER_PRIME_MS",
    "AUDIO_LOUDNESS_MAX_CUT_DB",
    "AUDIO_LOUDNESS_MAX_GAIN_DB",
    "AUDIO_LOUDNESS_MIN_VOICED",
    "AUDIO_LOUDNESS_PCT",
    "AUDIO_LOUDNESS_PEAK_CEIL",
    "AUDIO_LOUDNESS_TARGET_DBFS",
    "AUDIO_LOUDNESS_TOL_DB",
    "AUDIO_LOUDNESS_WIN_S",
    "AUDIO_HZ",
    "AUDIO_REF_MAX_S",
    "AUDIO_REF_MIN_VOICED_S",
    "AUDIO_REF_OFFICIAL_MAX",
    "AUDIO_REF_VOICE_REL",
    "AUDIO_RELEASE_TICKS",
    "AUDIO_SEAM_BED_FLOOR_DB",
    "AUDIO_SEAM_BED_GAIN_MAX_DB",
    "AUDIO_SEAM_BED_SELECT",
    "AUDIO_SEAM_BED_TILE_VOICED_FRAC",
    "AUDIO_SEAM_BED_VOICED_FRAC",
    "AUDIO_SEAM_BED_VOICED_K",
    "AUDIO_SEAM_BED_VOICED_SUSTAIN",
    "AUDIO_SEAM_FADE",
    "AUDIO_SEAM_PATCH",
    "AUDIO_SEAM_PATCH_GUARD_CENT_HZ",
    "AUDIO_SEAM_PATCH_GUARD_FLAT",
    "AUDIO_SEAM_PATCH_GUARD_HOP",
    "AUDIO_SEAM_PATCH_GUARD_K",
    "AUDIO_SEAM_PATCH_GUARD_LAYERS",
    "AUDIO_SEAM_PATCH_GUARD_MARGIN_S",
    "AUDIO_SEAM_PATCH_GUARD_MIN_S",
    "AUDIO_SEAM_PATCH_GUARD_STEP_DB",
    "AUDIO_SEAM_PATCH_GUARD_WIN",
    "AUDIO_SEAM_TILE",
    "AV_CONCAT_VIDEO_EXTS",
    "BASELINE_FLOOR_REL",
    "BLEND_SHAPES",
    "BLEND_SHAPE_DEFAULT",
    "BLUR_COLLAPSE_RATIO",
    "BLUR_COLLAPSE_RATIO_SHARP",
    "BLUR_RECOVER_RATIO",
    "BLUR_ZONE_RATIO",
    "BOUNDARY_JUMP_WARN",
    "FPS",
    "FRAME_PER_TOKEN",
    "FRAME_RESCALE",
    "GRADE_DEV_FLOOR",
    "GRADE_DEV_Z",
    "GUIDE_RUNS",
    "JUMP_RATIO",
    "KEY_EXPORT_FRAMES",
    "KEY_EXPORT_TAIL_AUDIO",
    "KEY_EXPORT_TAIL_VIDEO",
    "LOSSLESS_AUDIO_CODECS",
    "LOWFREQ_PULL_BLUR",
    "LOWFREQ_PULL_FRAMES",
    "LOWFREQ_PULL_WEIGHT",
    "MASK_MODES",
    "MATCH_PREV_FRAMES",
    "MATCH_PREV_GAIN_MAX",
    "MATCH_PREV_OFF_MAX",
    "MATCH_PREV_STATS_FRAMES",
    "MATCH_PREV_WEIGHT",
    "MAX_SETTLE",
    "PCM_UI_KEY",
    "POST_BODY_DISP_MAX",
    "PROMPT_SEPARATOR_MIN_DASHES",
    "QUANTILE_MAX_ELEMS",
    "QUANTILE_SAMPLE_ELEMS",
    "REPEAT_MAE",
    "REPEAT_MIN_RUN",
    "REPEAT_SCAN",
    "RUN_ID_TYPES",
    "RelayPlan",
    "SEAM_BLEND_TOP",
    "SEAM_BLEND_TOP_MAX",
    "SEAM_GHOST_ALPHA",
    "SEAM_GHOST_FRAMES",
    "SEAM_MIN_FLOOR",
    "SEAM_MIN_MASK",
    "SEAM_RAMP_TOP",
    "SEAM_RAMP_TOP_MAX",
    "SEAM_RAMP_TOP_MIN",
    "SEAM_TAPER_TOKENS",
    "SEAM_WINDOW_TOP",
    "SETTLE_CAP",
    "SETTLE_CROSS_SCALE",
    "SETTLE_RECOVER_TARGET",
    "SETTLE_REF_OFF",
    "SETTLE_REPEAT_PATH",
    "SETTLE_SCAN",
    "SETTLE_SHARPEN",
    "SETTLE_SHARPEN_FRAMES",
    "SETTLE_SHARPEN_MAX",
    "UPSCALE_CHUNK_FRAMES_DEFAULT",
    "UPSCALE_OVERLAP_DEFAULT",
    "VOICE_ANCHOR_MIN_STD",
    "WINDOW_SHAPES",
    "WINDOW_SHAPE_DEFAULT",
    "Z_JUMP",
    "_AUDIO_META_KEY",
    "_DeclickCtx",
    "_FILE_PATH_KEYS",
    "_ILLEGAL_IN_NAME",
    "_LAP_KERNELS",
    "_LATENT_META_KEY",
    "_abs_max",
    "_anchor_position",
    "_audio_parts",
    "_av_module",
    "_baseline_floor",
    "_blur_collapse",
    "_box_blur_hwc",
    "_canonicalize",
    "_declick_bg_at_cut",
    "_declick_envelope",
    "_declick_fade_in_at_cut",
    "_declick_fill",
    "_declick_find_events",
    "_declick_report",
    "_declick_suppress",
    "_decode_pcm",
    "_dtw_feat",
    "_file_record",
    "_frame_diffs",
    "_frame_rms",
    "_guard_features",
    "_guard_layers_pass",
    "_iter_file_records",
    "_lines_like_js",
    "_link_source",
    "_load_pcm_sidecar",
    "_looks_like_path",
    "_match_channels",
    "_nested_pair",
    "_pad_frames",
    "_partition_anchors",
    "_passthrough_video_stream",
    "_path_is_abs",
    "_path_split",
    "_quantile_capped",
    "_resample_to",
    "_rms_db",
    "_robust_stats",
    "_secs",
    "_sharpness",
    "_speech_onset_in_head",
    "_video_codec",
    "_voice_anchor_audio",
    "_voice_anchor_tail",
    "_voiced_frac_from_frames",
    "_voiced_grids",
    "_window_shape",
    "anchor_window_start",
    "apply_relay",
    "collect_run_ids",
    "assemble_mp4_segments",
    "assert_assembled",
    "assert_segments_joinable",
    "audio_from_latent",
    "audio_seam_patch",
    "audio_tail_from_latent",
    "audio_to_fp32",
    "auto_audio_ref_seconds",
    "bed_source_window_len",
    "bed_window_voiced_fraction",
    "borrow_detail_from_body",
    "boundary_jump_ratio",
    "build_anchor_ref",
    "build_bed",
    "build_continue_latent",
    "concat_mp4_segments",
    "count_official_audio_refs",
    "declick_gate",
    "declick_on_segment",
    "declick_transients",
    "deconv_head_zone",
    "describe_head_jump",
    "describe_latent",
    "detect_settle",
    "drift_curve",
    "dtw_residual",
    "find_head_jump",
    "find_nonvoiced_bed_window",
    "graph_downstream_rank",
    "head_metrics",
    "head_repeat_dtw",
    "join_audio_segments",
    "load_audio",
    "normalize_loudness",
    "load_av_latent",
    "lowfreq_pull",
    "match_hist_head_to_body",
    "match_prev_stats",
    "match_stats",
    "match_white_balance",
    "max_upscale_chunks",
    "nonvoiced_candidates",
    "observation_profile",
    "pick_bed_window",
    "pick_pcm_outputs",
    "pick_prompt_block",
    "pick_video_outputs",
    "pixel_frames",
    "plan_relay",
    "plan_run_id_sync",
    "resolve_run_id",
    "prefix_blend_weights",
    "prefix_ramp_weights",
    "prefix_taper_weights",
    "prefix_window_weights",
    "probe_mp4",
    "quietest_window",
    "robust_body",
    "save_audio",
    "speech_rms_db",
    "save_av_latent",
    "scan_head_jump",
    "scan_head_repeat",
    "seam_crossfade",
    "seam_ghost_blend",
    "segment_appearance_stats",
    "self_check",
    "sync_run_id",
    "settle_compensate",
    "sharpen_head_zone",
    "snap_guide_run",
    "split_prompt_blocks",
    "step_offsets",
    "steps_for_frames",
    "streams_from_latent",
    "target_level",
    "temporal_tile_upscale",
    "trim_audio_head",
    "trim_head_frames",
    "trim_jump_curve",
    "unsharp_frames",
    "upscale_chunk_plan",
    "video_from_latent",
    "video_tail_from_latent",
]

# ---------------------------------------------------------------------------
# 猴子补丁转发：让 `relay_core.X = v` 的赋值**落到所有持有 X 的子模块**。
#
# 🔴 为什么必须有：拆包后 `X` 的模块级全局在**子模块**里，而 `relay_core.X = v`
#   只改包对象自己的属性 ⇒ 子模块内部的调用者读到的还是旧值。单测靠这种写法
#   强制走分支（`SETTLE_REPEAT_PATH` / `_frame_rms` / `_passthrough_video_stream` /
#   `QUANTILE_*`）⇒ 不转发就会**静默失效**：断言照样绿，被测分支其实没进去。
#
# 🔴 为什么是「所有持有者」而不是「属主」：单文件时代只有一个 globals，改 X 对
#   **每个**读 X 的地方都生效。拆包后别的子模块用 `from ._grid import FPS` 把值
#   **拷了副本**（实测 26 个这样的名字）⇒ 只写属主的话，那些副本仍是旧值。
#   ⇒ 赋值必须**逐个持有者都写**，才算还原拆分前的语义。
#   ⚠️ 这不是「给用户用的 API」；它存在的唯一理由是**保住拆分前的语义**。
# ---------------------------------------------------------------------------
import sys
import types as _types

_SUBMODULES = (
    "_grid",
    "latent",
    "audio",
    "plan",
    "seam",
    "bridge",
    "metrics",
    "concat",
    "upscale",
    "prompt",
)

# 名字 -> **定义它的**子模块（用于回查归属；`__setattr__` 用的是 `_HOLDERS`）
_OWNER = {
    # _grid
    "AUDIO_HZ": "_grid",
    "FPS": "_grid",
    "FRAME_PER_TOKEN": "_grid",
    "FRAME_RESCALE": "_grid",
    "GUIDE_RUNS": "_grid",
    "KEY_EXPORT_FRAMES": "_grid",
    "KEY_EXPORT_TAIL_AUDIO": "_grid",
    "KEY_EXPORT_TAIL_VIDEO": "_grid",
    "pixel_frames": "_grid",
    "self_check": "_grid",
    "snap_guide_run": "_grid",
    "step_offsets": "_grid",
    "steps_for_frames": "_grid",
    # latent
    "_LATENT_META_KEY": "latent",
    "audio_from_latent": "latent",
    "audio_tail_from_latent": "latent",
    "load_av_latent": "latent",
    "save_av_latent": "latent",
    "streams_from_latent": "latent",
    "trim_audio_head": "latent",
    "trim_head_frames": "latent",
    "video_from_latent": "latent",
    "video_tail_from_latent": "latent",
    # audio
    "AUDIO_DECLICK_BG_PCT": "audio",
    "AUDIO_DECLICK_BG_WIN_MS": "audio",
    "AUDIO_DECLICK_CUT_GUARD_S": "audio",
    "AUDIO_DECLICK_EDGE_REL": "audio",
    "AUDIO_DECLICK_FADE_MS": "audio",
    "AUDIO_DECLICK_FALLBACK_S": "audio",
    "AUDIO_DECLICK_MAX_EVENTS": "audio",
    "AUDIO_DECLICK_MAX_LEN_MS": "audio",
    "AUDIO_DECLICK_PROBE_S": "audio",
    "AUDIO_DECLICK_QUIET_DBFS": "audio",
    "AUDIO_DECLICK_QUIET_REL": "audio",
    "AUDIO_DECLICK_RATIO": "audio",
    "AUDIO_DECLICK_SCOPE_ALL": "audio",
    "AUDIO_ENCODER_PRIME_MS": "audio",
    "AUDIO_LOUDNESS_MAX_CUT_DB": "audio",
    "AUDIO_LOUDNESS_MAX_GAIN_DB": "audio",
    "AUDIO_LOUDNESS_MIN_VOICED": "audio",
    "AUDIO_LOUDNESS_PCT": "audio",
    "AUDIO_LOUDNESS_PEAK_CEIL": "audio",
    "AUDIO_LOUDNESS_TARGET_DBFS": "audio",
    "AUDIO_LOUDNESS_TOL_DB": "audio",
    "AUDIO_LOUDNESS_WIN_S": "audio",
    "AUDIO_SEAM_BED_FLOOR_DB": "audio",
    "AUDIO_SEAM_BED_GAIN_MAX_DB": "audio",
    "AUDIO_SEAM_BED_SELECT": "audio",
    "AUDIO_SEAM_BED_TILE_VOICED_FRAC": "audio",
    "AUDIO_SEAM_BED_VOICED_FRAC": "audio",
    "AUDIO_SEAM_BED_VOICED_K": "audio",
    "AUDIO_SEAM_BED_VOICED_SUSTAIN": "audio",
    "AUDIO_SEAM_FADE": "audio",
    "AUDIO_SEAM_PATCH": "audio",
    "AUDIO_SEAM_PATCH_GUARD_CENT_HZ": "audio",
    "AUDIO_SEAM_PATCH_GUARD_FLAT": "audio",
    "AUDIO_SEAM_PATCH_GUARD_HOP": "audio",
    "AUDIO_SEAM_PATCH_GUARD_K": "audio",
    "AUDIO_SEAM_PATCH_GUARD_LAYERS": "audio",
    "AUDIO_SEAM_PATCH_GUARD_MARGIN_S": "audio",
    "AUDIO_SEAM_PATCH_GUARD_MIN_S": "audio",
    "AUDIO_SEAM_PATCH_GUARD_STEP_DB": "audio",
    "AUDIO_SEAM_PATCH_GUARD_WIN": "audio",
    "AUDIO_SEAM_TILE": "audio",
    "_AUDIO_META_KEY": "audio",
    "_DeclickCtx": "audio",
    "_audio_parts": "audio",
    "_declick_bg_at_cut": "audio",
    "_declick_envelope": "audio",
    "_declick_fade_in_at_cut": "audio",
    "_declick_fill": "audio",
    "_declick_find_events": "audio",
    "_declick_report": "audio",
    "_declick_suppress": "audio",
    "_frame_rms": "audio",
    "_guard_features": "audio",
    "_guard_layers_pass": "audio",
    "_match_channels": "audio",
    "_resample_to": "audio",
    "_rms_db": "audio",
    "_speech_onset_in_head": "audio",
    "_voiced_frac_from_frames": "audio",
    "audio_seam_patch": "audio",
    "audio_to_fp32": "audio",
    "bed_source_window_len": "audio",
    "bed_window_voiced_fraction": "audio",
    "build_bed": "audio",
    "declick_gate": "audio",
    "declick_on_segment": "audio",
    "declick_transients": "audio",
    "find_nonvoiced_bed_window": "audio",
    "join_audio_segments": "audio",
    "load_audio": "audio",
    "normalize_loudness": "audio",
    "nonvoiced_candidates": "audio",
    "pick_bed_window": "audio",
    "quietest_window": "audio",
    "save_audio": "audio",
    "speech_rms_db": "audio",
    "target_level": "audio",
    # plan
    "ANCHOR_VOICED_MARGIN_S": "plan",
    "ANCHOR_VOICED_MIN_FRAC": "plan",
    "AUDIO_REF_MAX_S": "plan",
    "AUDIO_REF_MIN_VOICED_S": "plan",
    "AUDIO_REF_OFFICIAL_MAX": "plan",
    "AUDIO_REF_VOICE_REL": "plan",
    "RelayPlan": "plan",
    "VOICE_ANCHOR_MIN_STD": "plan",
    "_anchor_position": "plan",
    "_partition_anchors": "plan",
    "_voice_anchor_audio": "plan",
    "_voice_anchor_tail": "plan",
    "_voiced_grids": "plan",
    "anchor_window_start": "plan",
    "apply_relay": "plan",
    "collect_run_ids": "plan",
    "plan_run_id_sync": "plan",
    "resolve_run_id": "plan",
    "sync_run_id": "plan",
    "RUN_ID_TYPES": "plan",
    "auto_audio_ref_seconds": "plan",
    "build_anchor_ref": "plan",
    "count_official_audio_refs": "plan",
    "match_stats": "plan",
    "plan_relay": "plan",
    # seam
    "ADVISE_WITHIN": "seam",
    "ANALYSIS_SHORT_SIDE": "seam",
    "ANALYSIS_SHORT_SIDE_ALT": "seam",
    "BASELINE_FLOOR_REL": "seam",
    "BLUR_COLLAPSE_RATIO": "seam",
    "BLUR_COLLAPSE_RATIO_SHARP": "seam",
    "BLUR_RECOVER_RATIO": "seam",
    "BLUR_ZONE_RATIO": "seam",
    "BOUNDARY_JUMP_WARN": "seam",
    "GRADE_DEV_FLOOR": "seam",
    "GRADE_DEV_Z": "seam",
    "JUMP_RATIO": "seam",
    "LOWFREQ_PULL_BLUR": "seam",
    "LOWFREQ_PULL_FRAMES": "seam",
    "LOWFREQ_PULL_WEIGHT": "seam",
    "MATCH_PREV_FRAMES": "seam",
    "MATCH_PREV_GAIN_MAX": "seam",
    "MATCH_PREV_OFF_MAX": "seam",
    "MATCH_PREV_STATS_FRAMES": "seam",
    "MATCH_PREV_WEIGHT": "seam",
    "MAX_SETTLE": "seam",
    "POST_BODY_DISP_MAX": "seam",
    "QUANTILE_MAX_ELEMS": "seam",
    "QUANTILE_SAMPLE_ELEMS": "seam",
    "REPEAT_MAE": "seam",
    "REPEAT_MIN_RUN": "seam",
    "REPEAT_SCAN": "seam",
    "SEAM_GHOST_ALPHA": "seam",
    "SEAM_GHOST_FRAMES": "seam",
    "SETTLE_CAP": "seam",
    "SETTLE_CROSS_SCALE": "seam",
    "SETTLE_RECOVER_TARGET": "seam",
    "SETTLE_REF_OFF": "seam",
    "SETTLE_REPEAT_PATH": "seam",
    "SETTLE_SCAN": "seam",
    "SETTLE_SHARPEN": "seam",
    "SETTLE_SHARPEN_FRAMES": "seam",
    "SETTLE_SHARPEN_MAX": "seam",
    "Z_JUMP": "seam",
    "_LAP_KERNELS": "seam",
    "_abs_max": "seam",
    "_baseline_floor": "seam",
    "_blur_collapse": "seam",
    "_box_blur_hwc": "seam",
    "_canonicalize": "seam",
    "_frame_diffs": "seam",
    "_quantile_capped": "seam",
    "_robust_stats": "seam",
    "_sharpness": "seam",
    "borrow_detail_from_body": "seam",
    "boundary_jump_ratio": "seam",
    "deconv_head_zone": "seam",
    "describe_head_jump": "seam",
    "describe_latent": "seam",
    "detect_settle": "seam",
    "find_head_jump": "seam",
    "head_metrics": "seam",
    "lowfreq_pull": "seam",
    "match_hist_head_to_body": "seam",
    "match_prev_stats": "seam",
    "match_white_balance": "seam",
    "observation_profile": "seam",
    "robust_body": "seam",
    "scan_head_jump": "seam",
    "scan_head_repeat": "seam",
    "seam_crossfade": "seam",
    "seam_ghost_blend": "seam",
    "settle_compensate": "seam",
    "sharpen_head_zone": "seam",
    "trim_jump_curve": "seam",
    "unsharp_frames": "seam",
    # bridge
    "AUDIO_RELEASE_TICKS": "bridge",
    "BLEND_SHAPES": "bridge",
    "BLEND_SHAPE_DEFAULT": "bridge",
    "MASK_MODES": "bridge",
    "SEAM_BLEND_TOP": "bridge",
    "SEAM_BLEND_TOP_MAX": "bridge",
    "SEAM_MIN_FLOOR": "bridge",
    "SEAM_MIN_MASK": "bridge",
    "SEAM_RAMP_TOP": "bridge",
    "SEAM_RAMP_TOP_MAX": "bridge",
    "SEAM_RAMP_TOP_MIN": "bridge",
    "SEAM_TAPER_TOKENS": "bridge",
    "SEAM_WINDOW_TOP": "bridge",
    "WINDOW_SHAPES": "bridge",
    "WINDOW_SHAPE_DEFAULT": "bridge",
    "_nested_pair": "bridge",
    "_window_shape": "bridge",
    "build_continue_latent": "bridge",
    "prefix_blend_weights": "bridge",
    "prefix_ramp_weights": "bridge",
    "prefix_taper_weights": "bridge",
    "prefix_window_weights": "bridge",
    # metrics
    "_dtw_feat": "metrics",
    "drift_curve": "metrics",
    "dtw_residual": "metrics",
    "head_repeat_dtw": "metrics",
    "segment_appearance_stats": "metrics",
    # concat
    "AV_CONCAT_VIDEO_EXTS": "concat",
    "LOSSLESS_AUDIO_CODECS": "concat",
    "PCM_UI_KEY": "concat",
    "_FILE_PATH_KEYS": "concat",
    "_ILLEGAL_IN_NAME": "concat",
    "_av_module": "concat",
    "_decode_pcm": "concat",
    "_file_record": "concat",
    "_iter_file_records": "concat",
    "_link_source": "concat",
    "_load_pcm_sidecar": "concat",
    "_looks_like_path": "concat",
    "_passthrough_video_stream": "concat",
    "_path_is_abs": "concat",
    "_path_split": "concat",
    "_secs": "concat",
    "_video_codec": "concat",
    "assemble_mp4_segments": "concat",
    "assert_assembled": "concat",
    "assert_segments_joinable": "concat",
    "concat_mp4_segments": "concat",
    "graph_downstream_rank": "concat",
    "pick_pcm_outputs": "concat",
    "pick_video_outputs": "concat",
    "probe_mp4": "concat",
    # upscale
    "UPSCALE_CHUNK_FRAMES_DEFAULT": "upscale",
    "UPSCALE_OVERLAP_DEFAULT": "upscale",
    "_pad_frames": "upscale",
    "max_upscale_chunks": "upscale",
    "temporal_tile_upscale": "upscale",
    "upscale_chunk_plan": "upscale",
    # prompt
    "PROMPT_SEPARATOR_MIN_DASHES": "prompt",
    "_lines_like_js": "prompt",
    "pick_prompt_block": "prompt",
    "split_prompt_blocks": "prompt",
}

# 名字 -> **所有持有它的**子模块（属主 + 用 `from .X import name` 拷了副本的）
_HOLDERS = {}
for _mn in _SUBMODULES:
    _mod = sys.modules[__name__ + "." + _mn]
    for _k in _OWNER:
        if _k in vars(_mod):
            _HOLDERS.setdefault(_k, []).append(_mn)


class _RelayCoreModule(_types.ModuleType):
    """把对**已导出名**的赋值转发给所有持有它的子模块（见上方说明）。"""

    def __setattr__(self, name, value):
        for _mn in _HOLDERS.get(name, ()):        # `_HOLDERS` 是类外全局，不触发本方法
            setattr(sys.modules[__name__ + "." + _mn], name, value)
        super().__setattr__(name, value)


sys.modules[__name__].__class__ = _RelayCoreModule
